"""Markdown report rendering."""

from __future__ import annotations

from collections import Counter
from typing import Any

DISCLAIMER = (
    "This report is generated by rule-based strategy scans for self-directed analysis. "
    "It is not financial advice, not a buy/sell recommendation, and does not guarantee returns. "
    "Always verify data and make your own decisions."
)


def _line_for_signal(signal: dict[str, Any]) -> str:
    parts = [
        f"- {signal['symbol']} | {signal['strategy']} | {signal['status']} | score {signal['score']} | close {signal['close']}",
    ]
    if signal.get("entry") is not None:
        parts.append(f"entry trigger {signal['entry']}")
    if signal.get("stop_loss") is not None:
        parts.append(f"stop {signal['stop_loss']}")
    if signal.get("risk_reward") is not None:
        parts.append(f"R:R {signal['risk_reward']}")
    parts.append(signal["reason"])
    return " | ".join(parts)


def render_evening_report(payload: dict[str, Any]) -> str:
    summary = payload.get("summary", {})
    signals = payload.get("signals", [])
    report_date = payload.get("report_date", "unknown")

    by_strategy = Counter(signal["strategy"] for signal in signals)
    by_status = Counter(signal["status"] for signal in signals)
    watchlist_candidates = [
        signal for signal in signals if signal["status"] in {"actionable", "watchlist"}
    ][:10]
    avoid_list = [signal for signal in signals if signal["status"] == "avoid"][:10]

    lines = [
        "# ArthaVyuh Evening Report",
        "",
        f"Date: {report_date}",
        "",
        "## Summary",
        "",
        f"- Total symbols scanned: {summary.get('total_symbols_scanned', 0)}",
        f"- Total strategy runs: {summary.get('total_strategies_run', 0)}",
        f"- Total signals: {summary.get('signals_generated', len(signals))}",
        f"- Symbols skipped: {summary.get('symbols_skipped_count', 0)}",
        f"- Errors: {summary.get('errors_count', 0)}",
        "",
        "## Signals by Strategy",
        "",
    ]

    if by_strategy:
        lines.extend(f"- {strategy}: {count}" for strategy, count in sorted(by_strategy.items()))
    else:
        lines.append("- None")

    lines.extend(["", "## Signals by Status", ""])
    if by_status:
        lines.extend(f"- {status}: {count}" for status, count in sorted(by_status.items()))
    else:
        lines.append("- None")

    lines.extend(["", "## Top Watchlist Candidates", ""])
    if watchlist_candidates:
        lines.extend(_line_for_signal(signal) for signal in watchlist_candidates)
    else:
        lines.append("- None")

    lines.extend(["", "## Avoid List", ""])
    if avoid_list:
        lines.extend(_line_for_signal(signal) for signal in avoid_list)
    else:
        lines.append("- None")

    lines.extend(["", "## Errors and Skipped Symbols", ""])
    skipped = summary.get("symbols_skipped", [])
    errors = summary.get("errors", [])
    if not skipped and not errors:
        lines.append("- None")
    for item in skipped:
        lines.append(f"- Skipped {item['symbol']}: {item['reason']}")
    for item in errors:
        lines.append(f"- Error {item['symbol']} / {item['strategy']}: {item['reason']}")

    lines.extend(["", "## Disclaimer", "", DISCLAIMER, ""])
    return "\n".join(lines)
